name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: manojshr-kan/kan-cloud-platform-ci/.github/actions/maven-verify@main

  build-and-push:
    needs: test
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4

      - id: version
        uses: manojshr-kan/kan-cloud-platform-ci/.github/actions/resolve-version@main

      - id: ecr
        uses: manojshr-kan/kan-cloud-platform-ci/.github/actions/ecr-login@main
        with:
          role_arn: ${{ vars.AWS_ROLE_ARN }}
          region: ${{ vars.AWS_REGION }}

      - uses: manojshr-kan/kan-cloud-platform-ci/.github/actions/docker-build-push@main
        with:
          registry: ${{ steps.ecr.outputs.registry }}
          image_name: payment-api
          immutable_tag: ${{ steps.version.outputs.immutable }}
          rolling_tag: ${{ steps.version.outputs.rolling }}
